//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by HeizkalenderInstallation.rc
//
#define IDCANCEL2                       4
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDS_TITLE                       102
#define IDP_SOCKETS_INIT_FAILED         103
#define IDS_PAGE_CONNECT                104
#define IDS_PAGE_SETTINGS               105
#define IDP_NEED_CONNECTION             106
#define IDD_PAGE_CONNECT                107
#define IDS_PAGE_SYSVAR                 107
#define IDD_PAGE_SETTINGS               108
#define IDS_PAGE_PROGRAMS               108
#define IDD_PAGE_PROGRAMS               109
#define IDS_PAGE_ROOMS                  109
#define IDD_PAGE_SYSVARS                110
#define IDS_MODE_CHURCHTOOLS            110
#define IDD_PAGE_ROOMS                  111
#define IDS_MODE_CHURCHDESK_ICAL        111
#define IDD_WARNING                     112
#define IDS_MODE_CHURCHDESK_API         112
#define IDP_FILES_MISSING               113
#define IDP_UNKNOWN_PROGRAMS            114
#define IDS_UNVERAENDERT                114
#define IDP_NEWER_PROGRAMS              115
#define IDP_CHOOSE_MODE_MANUAL          116
#define IDP_CHOOSE_NEW_MODE             117
#define IDP_CCU_UPDATE_SUCCESSFUL       118
#define IDP_CCU_UPDATE_FAILED           119
#define IDP_CCU_NO_UPDATE               120
#define IDP_QUERY_UPDATE                121
#define IDP_QUERY_UPDATE_SIMUATION      121
#define IDS_TITLE_PROGRAMS              122
#define IDS_INST_NEW                    123
#define IDS_INST_REPLACED               124
#define IDS_INST_UPDATED                125
#define IDS_INST_NOACTION               126
#define IDP_KURVEN_WERTE_AUFSTEIGEND    127
#define IDR_MAINFRAME                   128
#define IDP_NO_ROOMS                    128
#define IDP_LOGIN_DATA_REQUIERED        129
#define IDP_MODE_SWITCH_WARNING         130
#define IDP_QUERY_MODE_SWITCH_WARNING   130
#define IDP_MODE_SWITCH_WARNING_RES     131
#define IDP_QUERY_MODE_SWITCH_WARNING_RES 131
#define IDP_RAUM_LISTEN_UNSYMETRISCH    132
#define IDP_TEST_AKTOR_SCHALTEN         132
#define IDP_NEED_MODE                   133
#define IDP_FILE_INVALID                134
#define IDP_DATA_MODIFIED               135
#define IDD_DIALOG1                     135
#define IDD_ROOM                        135
#define IDP_QUERY_DATA_MODIFIED         135
#define IDP_RAUM_LISTEN_NICHT_LEER      136
#define IDP_QUERY_RAUMLISTEN_NICHT_LEER 136
#define IDD_PAGE_RESOURCES              136
#define IDP_LESEN_VON_CHURCHTOOLS_FEHLGESCHLAGEN 137
#define IDS_TITLE_SYSVARS               138
#define IDD_RESSOURCE                   138
#define IDS_NEW                         139
#define IDS_UPDATE                      140
#define IDD_SYSVAR                      140
#define IDS_TITLE_ROOMS                 141
#define IDS_SIMULATION                  142
#define IDP_SIMULATION_GESTARTET        143
#define IDP_QUERY_SIMULATION_LADEN      144
#define IDP_QUERY_UPDATE_CCU            145
#define IDP_RAUMVAR_NAMEN_KORREKTUR     146
#define IDS_TITLE_ROOMS2                147
#define IDS_TITLE_RESOURCES             147
#define IDS_PAGE_RESOURCES              148
#define IDS_RAUM_MODUS                  149
#define IDS_RAUM_DEVTYP                 150
#define IDS_NEW_ROOM                    151
#define IDP_QUERY_DELETE_ROOM           152
#define IDP_RAUM_NAME_EXISTIERT         153
#define IDP_RAUM_NAME_FEHLT             154
#define IDP_RAUMVAR_NAMEN_KORREKTUR2    155
#define IDP_RAUMVAR_NAMEN_FEHLEN        155
#define IDP_TEST_AKTOR_HEIZEN           156
#define IDP_RAUMLISTE_WURDE_AKTUALISIERT 157
#define IDP_RAUMLISTE_WURDE_NICHT_AKTUALISIERT 158
#define IDS_AN_AUS                      159
#define IDP_LESEN_VON_CHURCHDESK_FEHLGESCHLAGEN 160
#define IDS_INST_IGNORED                161
#define IDP_WINMERGE_NICHT_GEFUNDEN     162
#define IDS_VERSION_ALT                 163
#define IDS_VERSION_NEU                 164
#define IDS_VERBINDUNGSAUGBAU_FEHLGESCHLAGEN 165
#define IDS_MODE_ICAL                   166
#define IDS_MODE_GOOGLE                 167
#define IDP_RAUMLISTE_UNGUELTIG         168
#define IDP_PROGRAMME_KONTROLLIEREN     169
#define IDP_SYSVARS_KONTROLLIEREN       170
#define IDP_RAUMLISTE_KONTROLLIEREN     171
#define IDS_LEERER_NAME                 172
#define IDP_QUERY_DELETE_RESOURCE       173
#define IDP_QUERY_ALLE_RESSOURCEN_LESEN 174
#define IDP_TEST_AKTOR_HEIZENSCHALTEN   175
#define IDP_AKTOREN_FUER_HEIZENSCHALTEN_LEER 176
#define IDP_PROGRAMME_NICHT_AKTUALISIERT 177
#define IDC_TEST                        1000
#define IDC_BT_CONNECT                  1000
#define IDC_ED_HOST                     1001
#define IDC_ED_USERNAME                 1002
#define IDC_ED_PASSWORD                 1003
#define IDC_ED_PREFIX                   1004
#define IDC_ED_CHURCHNAME               1005
#define IDC_ABOUT                       1006
#define IDC_ST_COPYRIGHT                1007
#define IDC_ED_LOGINTOKEN               1007
#define IDC_ST_VERSION                  1008
#define IDC_CH_DONT_SHOW_AGAIN          1009
#define IDC_ED_ORGAID                   1009
#define IDC_CB_MODE                     1010
#define IDC_ED_APITOKEN                 1011
#define IDC_ST_CHURCHTOOL1              1012
#define IDC_ST_CHURCHTOOL2              1013
#define IDC_ST_CHURCHDESK1              1014
#define IDC_ST_CHURCHDESK2              1015
#define IDC_BT_READRES                  1016
#define IDC_CH_LOG1                     1017
#define IDC_ST_CHURCHTOOL3              1017
#define IDC_ST_ICAL_GOOGLE              1017
#define IDC_ST_RAUMLISTE                1017
#define IDC_LC_PROGRAMS                 1018
#define IDC_ED_LOGINTOKEN2              1018
#define IDC_ED_RAUMLISTE                1018
#define IDC_CH_LOG                      1019
#define IDC_CH_LOG2                     1020
#define IDC_CH_LOG_HEIZKURVE            1022
#define IDC_CH_HANDGRUNDTEMP            1023
#define IDC_CH_HANDTEMP                 1024
#define IDC_ED_GRUNDTEMP                1025
#define IDC_ED_ATEMPGRENZE              1026
#define IDC_ED_VORZEIT_AN               1026
#define IDC_ED_KURVE_1                  1027
#define IDC_ED_VORZEIT_AUS              1027
#define IDC_ED_KURVE_2                  1028
#define IDC_BUTTON1                     1028
#define IDC_BT_NEW                      1028
#define IDC_ED_FAKTOR                   1028
#define IDC_ED_KURVE_3                  1029
#define IDC_BUTTON2                     1029
#define IDC_BT_MODIFY                   1029
#define IDC_BT_TEST                     1029
#define IDC_ED_KURVE_4                  1030
#define IDC_BUTTON3                     1030
#define IDC_BT_DELETE                   1030
#define IDC_ED_KURVE_5                  1031
#define IDC_LC_SYSVARS                  1031
#define IDC_ED_KURVE_6                  1032
#define IDC_LC_ROOMS                    1032
#define IDC_ED_KURVE_7                  1033
#define IDC_CB_MODFE                    1033
#define IDC_ED_KURVE_8                  1034
#define IDC_CB_GERAETETYP               1034
#define IDC_CB_AKTOR1                   1035
#define IDC_ED_TEMP                     1036
#define IDC_ED_NAME                     1037
#define IDC_ED_WERT_NEU                 1038
#define IDC_CB_AKTOR2                   1038
#define IDC_LINK1                       1038
#define IDC_LC_DATA                     1039
#define IDC_LINK2                       1039
#define IDC_LB_DATA                     1040
#define IDC_ED_STATUS                   1040
#define IDC_BT_WINMERGE                 1041
#define IDC_ED_PROTOKOLLIERT            1041
#define IDC_ED_ID                       1043
#define IDC_BT_INFO                     1044
#define IDC_ED_TYP                      1045
#define IDC_ED_WERT_ALT                 1046
#define IDC_ED_ICALURL                  1047
#define IDC_ST_ICALURL                  1048
#define IDC_ST_GOOGLE1                  1049
#define IDC_ST_GOOGLE2                  1050
#define IDC_ED_GOOGLE_APIKEY            1051
#define IDC_ED_GOOGLE_KALID             1052

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        142
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1053
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
